In [50]:
import pandas as pd

In [51]:
hate_df = pd.read_csv("/content/drive/MyDrive/Portofolio J/Multi Detector/hatespeech.csv")

In [52]:
hate_df.head(10)

,Unnamed: 0,count,hate_speech,offensive_language,neither,class,tweet
0,0,3,0,0,3,2,!!! RT @mayasolovely: As a woman you shouldn't...
1,1,3,0,3,0,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2,2,3,0,3,0,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3,3,3,0,2,1,1,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4,4,6,0,6,0,1,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...
5,5,3,1,2,0,1,"!!!!!!!!!!!!!!!!!!""@T_Madison_x: The shit just..."
6,6,3,0,3,0,1,"!!!!!!""@__BrighterDays: I can not just sit up ..."
7,7,3,0,3,0,1,!!!!&#8220;@selfiequeenbri: cause I'm tired of...
8,8,3,0,3,0,1,""" &amp; you might not get ya bitch back &amp; ..."
9,9,3,1,2,0,1,""" @rhythmixx_ :hobbies include: fighting Maria..."

In [53]:
emotion_df = pd.read_csv("/content/drive/MyDrive/Portofolio J/Multi Detector/emotion.csv")

In [54]:
emotion_df.head(100)

    Unnamed: 0                                               text  label
0            0      i just feel really helpless and heavy hearted      4
1            1  ive enjoyed being able to slouch about relax a...      0
2            2  i gave up my internship with the dmrg and am f...      4
3            3                         i dont know i feel so lost      0
4            4  i am a kindergarten teacher and i am thoroughl...      4
..         ...                                                ...    ...
95          95  i feel like i havent had a moment to breathe s...      1
96          96  i am feeling helpless because he is who the re...      0
97          97  i had not been in a convertible in many many y...      1
98          98  i feel like a whiner because my pain is really...      0
99          99  i feel like it is chipping away at my heart bi...      0

[100 rows x 3 columns]

In [55]:
violence_df = pd.read_csv("/content/drive/MyDrive/Portofolio J/Multi Detector/gender-based-violence-tweet-classification-challenge/Train.csv")

In [56]:
violence_df.head(10)

,Tweet_ID,tweet,type
0,ID_0022DWKP,Had a dream i got raped last night. By a guy i...,sexual_violence
1,ID_00395QYM,he thought the word raped means sex and told m...,sexual_violence
2,ID_003EOSSF,She NOT TALKING TO ME I WAS RAPED BY 2 MEN 1 M...,sexual_violence
3,ID_004BBHOD,I was sexually abused for 3 years at age 4 to ...,sexual_violence
4,ID_004F7516,Chessy Prout can do better by telling the trut...,sexual_violence
5,ID_0052TYKI,"Yes men rape women. But women also rape men, y...",sexual_violence
6,ID_0058QG76,"My Husband Beats Me Frequently, Wife Tells Cou...",Physical_violence
7,ID_005VM1DJ,Pretty sure he raped a 16yr old girl with 2 fr...,sexual_violence
8,ID_0060BW8R,TW sorry to hear that and yeah he recently th...,sexual_violence
9,ID_007FAIEI,"""I understand that... My father was abusive as...",sexual_violence

data preprocessing

In [57]:
emotion_df.drop(columns = ['Unnamed: 0'], inplace = True)
violence_df.drop(columns = ['Tweet_ID'], inplace = True)
hate_df = hate_df[['tweet', 'class']]

In [58]:
emotion_df.head()

                                                text  label
0      i just feel really helpless and heavy hearted      4
1  ive enjoyed being able to slouch about relax a...      0
2  i gave up my internship with the dmrg and am f...      4
3                         i dont know i feel so lost      0
4  i am a kindergarten teacher and i am thoroughl...      4

In [59]:
violence_df.head()

                                               tweet             type
0  Had a dream i got raped last night. By a guy i...  sexual_violence
1  he thought the word raped means sex and told m...  sexual_violence
2  She NOT TALKING TO ME I WAS RAPED BY 2 MEN 1 M...  sexual_violence
3  I was sexually abused for 3 years at age 4 to ...  sexual_violence
4  Chessy Prout can do better by telling the trut...  sexual_violence

In [60]:
hate_df.head()

                                               tweet  class
0  !!! RT @mayasolovely: As a woman you shouldn't...      2
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...      1
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...      1
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...      1
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...      1

In [61]:
emotion_df.columns, violence_df.columns, hate_df.columns

(Index(['text', 'label'], dtype='object'),
 Index(['tweet', 'type'], dtype='object'),
 Index(['tweet', 'class'], dtype='object'))

In [62]:
violence_df.rename(columns = {'tweet' : 'text', 'type' : 'label'}, inplace = True)
hate_df.rename(columns = {'tweet' : 'text', 'class' : 'label'}, inplace = True)

In [63]:
emotion_df.columns, violence_df.columns, hate_df.columns

(Index(['text', 'label'], dtype='object'),
 Index(['text', 'label'], dtype='object'),
 Index(['text', 'label'], dtype='object'))

In [64]:
emotion_df.isna().sum(), violence_df.isna().sum(), hate_df.isna().sum()

(text     0
 label    0
 dtype: int64,
 text     0
 label    0
 dtype: int64,
 text     0
 label    0
 dtype: int64)

In [65]:
emotion_df.shape, violence_df.shape, hate_df.shape

((416809, 2), (39650, 2), (24783, 2))

extract 12 thousand rows dari tiap dataset

In [66]:
emotion_df['label'].value_counts()

label
1    141067
0    121187
3     57317
4     47712
2     34554
5     14972
Name: count, dtype: int64

In [67]:
emo_df = pd.DataFrame()
for i in range(6):
  subset = emotion_df[emotion_df['label'] == i].sample(n=2000, random_state=22)
  emo_df = pd.concat([emo_df, subset])

In [68]:
emo_df.shape

(12000, 2)

In [69]:
emotion_df = emo_df.copy()

In [70]:
emotion_df['label'].value_counts()

label
0    2000
1    2000
2    2000
3    2000
4    2000
5    2000
Name: count, dtype: int64

In [71]:
violence_df['label'].value_counts()

label
sexual_violence                 32648
Physical_violence                5946
emotional_violence                651
economic_violence                 217
Harmful_Traditional_practice      188
Name: count, dtype: int64

In [72]:
sexual_vio = violence_df[violence_df['label'] == 'sexual_violence'].sample(n=4998, random_state=22)
violence_df = violence_df[violence_df['label'] != 'sexual_violence']

In [73]:
violence_df.shape

(7002, 2)

In [74]:
violence_df = pd.concat([violence_df, sexual_vio], axis=0)

In [75]:
violence_df.shape

(12000, 2)

In [76]:
hate_df['label'].value_counts()

label
1    19190
2     4163
0     1430
Name: count, dtype: int64

In [79]:
h_df = hate_df[hate_df['label'] == 1].sample(n=6407, random_state=22)
hate_df = hate_df[hate_df['label'] != 1]

In [81]:
hate_df.shape

(5593, 2)

In [82]:
hate_df = pd.concat([hate_df, h_df], axis=0)

In [83]:
hate_df.shape

(12000, 2)

In [84]:
emotion_df.shape, violence_df.shape, hate_df.shape

((12000, 2), (12000, 2), (12000, 2))

In [85]:
emotion_df.head(5)

                                                     text  label
98053   i believe our social and crime problems around...      0
266567  ive been guilty of it and afterward i feel awf...      0
163879  i feel the need to apologize for the messy loo...      0
132605  i feel the onus of a heartbroken fever washing...      0
32085             i feel need to be stressed to be shared      0

In [86]:
hate_df.head(5)

                                                 text  label
0   !!! RT @mayasolovely: As a woman you shouldn't...      2
40    " momma said no pussy cats inside my doghouse "      2
63  "@Addicted2Guys: -SimplyAddictedToGuys http://...      2
66  "@AllAboutManFeet: http://t.co/3gzUpfuMev" woo...      2
67  "@Allyhaaaaa: Lemmie eat a Oreo &amp; do these...      2

In [87]:
violence_df.head(5)

                                                 text              label
6   My Husband Beats Me Frequently, Wife Tells Cou...  Physical_violence
29  Best thing for me to do, is remain silent when...  Physical_violence
30  My husband will never beat me, Bambam denies r...  Physical_violence
33  theyre like, i just wanna be a baby maker with...  Physical_violence
35  I was in England for a week, the longest I’ve ...  Physical_violence

In [ ]:
#res